services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api_full
    container_name: ml_api
    ports:
      - "8000:8000"
    networks:
      - ml_net
    volumes:
      - ./outputs:/app/outputs

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    container_name: ml_frontend
    ports:
      - "8501:8501"
    networks:
      - ml_net
    depends_on:
      - api
    volumes:
      - ./outputs:/app/outputs

networks:
  ml_net:
    driver: bridge
